import { defineConfig } from "tsdown";

export default defineConfig({
  entry: [
    "src/index.ts",
    "src/core.ts",
    "src/tabs.ts",
    "src/dialog.ts",
    "src/alert-dialog.ts",
    "src/accordion.ts",
    "src/popover.ts",
    "src/hover-card.ts",
    "src/tooltip.ts",
    "src/collapsible.ts",
    "src/navigation-menu.ts",
    "src/dropdown-menu.ts",
    "src/switch.ts",
    "src/radio-group.ts",
    "src/toggle.ts",
    "src/toggle-group.ts",
    "src/select.ts",
    "src/combobox.ts",
    "src/command.ts",
  ],
  format: ["esm", "cjs"],
  dts: true,
  clean: true,
  treeshake: true,
  hash: false,
  minify: true,
});
